import { IconName } from '@/components/common'

/**
 * List of icons to display in the icon picker
 * These can be modified to set the default icons that are shown in the 'create category' modal
 * Reference Twitter Bootstrap Icons for the list of available icons and their names:
 * https://icons.getbootstrap.com/
 */
export const iconPickerIcons: IconName[] = [
  'ChatFill',
  'PencilFill',
  'Truck',
  'TelephoneFill',
  'ChevronLeft',
  'ChevronRight',
  'ArrowUp',
  'ArrowDown',
  'ArrowClockwise',
  'EnvelopeFill',
  'FolderFill',
  'VolumeUpFill',
  'CurrencyEuro',
  'CurrencyDollar',
  'SunFill',
  'Square',
  'SquareFill',
  'FlagFill',
  'EyeFill',
  'PrinterFill',
  'ChatDotsFill',
  'MapFill',
  'CheckCircle',
  'Circle',
  'CircleFill',
  'Hexagon',
  'HexagonFill',
  'PuzzleFill',
  'StarFill',
  'Film',
  'CaretUp',
  'CaretDown',
  'CaretLeft',
  'CaretRight',
  'CloudFill',
  'CloudDownloadFill',
  'CloudUploadFill',
  'Code',
  'ClipboardFill',
  'CollectionFill',
  'GearFill',
  'Heart',
  'HouseFill',
  'BalloonFill',
  'AirplaneFill',
  'SuitClubFill',
  'SuitDiamondFill',
  'SuitHeartFill',
  'SuitSpadeFill',
  'CalendarDateFill'
]
